"""Replicator script generated by finops-governor (M9 adapter).

plan:  r1-ref
scene: r1-ref (120 variations)
Run inside Isaac Sim (headless):
  ./python.sh <this file>   # or via isaac-sim.headless with script arg
"""

import omni.replicator.core as rep

rep.settings.set_render_pathtraced(samples_per_pixel=128)

with rep.new_layer():
    environment = rep.create.from_usd('/kit/assets/floor.usda')
    asset_0 = rep.create.from_usd('/kit/assets/arm.usda')  # arm
    asset_1 = rep.create.from_usd('/kit/assets/box.usda')  # box
    assets = rep.create.group([asset_0, asset_1])

    camera_0 = rep.create.camera(position=(0.0, 2.0, 6.0), rotation=(-15.0, 0.0, 0.0))  # cam
    render_products = [rep.create.render_product(camera_0, (1920, 1080))]

    with rep.trigger.on_frame(num_frames=120):
        rep.modify.pose(input_prims=assets, rotation=rep.distribution.choice([(0, y, 0) for y in [0.0, 32.7273, 65.4545, 98.1818, 130.9091, 163.6364, 196.3636, 229.0909, 261.8182, 294.5455, 327.2727, 360.0]]))  # azimuth
        rep.create.light(light_type='Sphere', position=(0, 4, 0), intensity=rep.distribution.choice([500.0, 1000.0, 1500.0, 2000.0, 2500.0]))  # lighting

    writer = rep.WriterRegistry.get("BasicWriter")
    writer.initialize(output_dir='/kit/out/r1_ref', rgb=True)
    writer.attach(render_products)
