"""Replicator script generated by finops-governor (M9 adapter).

plan:  s4-bigscene
scene: s4-bigscene (150 variations)
Standalone headless execution (M9.2-validated form):
  docker run ... --entrypoint /isaac-sim/python.sh <image> <this file>
"""

from isaacsim import SimulationApp

simulation_app = SimulationApp({"headless": True})

import omni.replicator.core as rep

rep.settings.set_render_pathtraced(samples_per_pixel=128)

with rep.new_layer():
    environment = rep.create.from_usd('/kit/assets/floor.usda')
    asset_0 = rep.create.from_usd('/kit/assets/arm.usda')  # arm-0
    asset_1 = rep.create.from_usd('/kit/assets/box.usda')  # box-0
    asset_2 = rep.create.from_usd('/kit/assets/arm.usda')  # arm-1
    asset_3 = rep.create.from_usd('/kit/assets/box.usda')  # box-1
    asset_4 = rep.create.from_usd('/kit/assets/arm.usda')  # arm-2
    asset_5 = rep.create.from_usd('/kit/assets/box.usda')  # box-2
    asset_6 = rep.create.from_usd('/kit/assets/arm.usda')  # arm-3
    asset_7 = rep.create.from_usd('/kit/assets/box.usda')  # box-3
    asset_8 = rep.create.from_usd('/kit/assets/arm.usda')  # arm-4
    asset_9 = rep.create.from_usd('/kit/assets/box.usda')  # box-4
    asset_10 = rep.create.from_usd('/kit/assets/arm.usda')  # arm-5
    asset_11 = rep.create.from_usd('/kit/assets/box.usda')  # box-5
    assets = rep.create.group([asset_0, asset_1, asset_2, asset_3, asset_4, asset_5, asset_6, asset_7, asset_8, asset_9, asset_10, asset_11])

    camera_0 = rep.create.camera(position=(0.0, 3.0, 9.0), look_at=(0, 0, 0))  # cam
    render_products = [rep.create.render_product(camera_0, (1920, 1080))]

    scene_light = rep.create.light(light_type='Dome', intensity=1000.0)

    with rep.trigger.on_frame(num_frames=150):
        rep.modify.pose(input_prims=assets, rotation=rep.distribution.choice([(0, y, 0) for y in [0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0, 270.0, 300.0, 330.0]]))  # azimuth
        rep.modify.pose(input_prims=assets, position=rep.distribution.choice([(x, 0, x) for x in [-3.0, -2.1429, -1.2857, -0.4286, 0.4286, 1.2857, 2.1429, 3.0]]))  # position
        rep.modify.attribute('intensity', rep.distribution.choice([500.0, 1000.0, 1500.0, 2000.0, 2500.0]), input_prims=scene_light)  # lighting

    writer = rep.WriterRegistry.get("BasicWriter")
    writer.initialize(output_dir='/kit/out/s4_bigscene', rgb=True)
    writer.attach(render_products)

rep.orchestrator.run_until_complete()
simulation_app.close()
