"""Replicator script generated by finops-governor (M9 adapter).

plan:  s4-demo-governed
scene: arm-assembly-floor (96 variations)
Standalone headless execution (M9.2-validated form):
  docker run ... --entrypoint /isaac-sim/python.sh <image> <this file>
"""

from isaacsim import SimulationApp

simulation_app = SimulationApp({"headless": True})

import omni.replicator.core as rep

rep.settings.set_render_pathtraced(samples_per_pixel=128)

with rep.new_layer():
    environment = rep.create.from_usd('/kit/assets/floor.usda')
    asset_0 = rep.create.from_usd('/kit/assets/arm.usda')  # arm
    asset_1 = rep.create.from_usd('/kit/assets/box.usda')  # box
    assets = rep.create.group([asset_0, asset_1])

    camera_0 = rep.create.camera(position=(0.0, 2.0, 6.0), look_at=(0, 0, 0))  # cam
    render_products = [rep.create.render_product(camera_0, (1920, 1080))]

    scene_light = rep.create.light(light_type='Dome', intensity=1000.0)

    with rep.trigger.on_frame(num_frames=96):
        rep.modify.pose(input_prims=assets, rotation=rep.distribution.choice([(0, y, 0) for y in [0.0, 30.0, 60.0, 90.0, 120.0, 150.0, 180.0, 210.0, 240.0, 270.0, 300.0, 330.0]]))  # azimuth
        rep.modify.attribute('intensity', rep.distribution.choice([500.0, 1000.0, 1500.0, 2000.0, 2500.0]), input_prims=scene_light)  # lighting

    writer = rep.WriterRegistry.get("BasicWriter")
    writer.initialize(output_dir='/kit/out/s4_demo', rgb=True)
    writer.attach(render_products)

rep.orchestrator.run_until_complete()
simulation_app.close()
