"""Plan-to-Replicator adapter (M9, Task 9.4).

Crosses the boundary documented in docs/geometry-model.md section 2 since M5: a
GenerationPlan becomes a standalone, runnable Omniverse Replicator script for Isaac
Sim. The governor governs the plan; this adapter makes the plan executable on the real
industry stack - the emitted script IS the calibration workload (docs/calibration.md,
section 3) and the demo renderer.

Design (v1, limits stated):

* **Emits a script, never connects.** Generation is pure string assembly - buildable
  and testable without Isaac Sim; only running the output needs an RTX GPU.
* **Randomization maps through a registry** of known parameter kinds (rotation/pose,
  scatter/position, light intensity, color). Declared `levels` are honored via
  discretized `rep.distribution.choice`. Unknown parameter names are SKIPPED with a
  warning comment in the emitted script - the declared-input trust made visible, the
  same philosophy as the diversity plausibility warnings.
* **Single-scene plans only.** Multi-scene raises AdapterError; the calibration and
  demo workloads are single-scene, and the limit is documented rather than hidden.
* Modalities map to BasicWriter annotators; POSE has no BasicWriter equivalent and is
  skipped with a warning comment.
"""

from finops_governor.schemas import (
    GenerationPlan,
    OutputModality,
    RandomizationParameter,
    RendererType,
    Scene,
)

_WRITER_FLAGS: dict[OutputModality, str] = {
    OutputModality.RGB: "rgb",
    OutputModality.DEPTH: "distance_to_camera",
    OutputModality.SURFACE_NORMALS: "normals",
    OutputModality.SEMANTIC_SEGMENTATION: "semantic_segmentation",
    OutputModality.INSTANCE_SEGMENTATION: "instance_segmentation",
    OutputModality.BBOX_2D: "bounding_box_2d_tight",
    OutputModality.BBOX_3D: "bounding_box_3d",
}

# The v1 registry: substrings of a declared parameter name -> randomizer kind.
_PARAM_KINDS: list[tuple[tuple[str, ...], str]] = [
    (("rot", "azimuth", "yaw", "orientation"), "rotation"),
    (("pos", "scatter", "translat", "placement"), "position"),
    (("light", "intensity", "illum"), "light"),
    (("color", "colour", "material", "albedo"), "color"),
]


class AdapterError(Exception):
    """The plan cannot be adapted; the reason names the v1 limit that was hit."""


def generate_replicator_script(plan: GenerationPlan, output_dir: str = "_output") -> str:
    """Emit a standalone Replicator script for a single-scene GenerationPlan."""
    if len(plan.scenes) != 1:
        raise AdapterError(
            f"v1 adapts single-scene plans only; plan '{plan.plan_id}' has "
            f"{len(plan.scenes)} scenes (see module docstring)."
        )
    scene = plan.scenes[0]
    rs = plan.render_settings

    lines: list[str] = []
    add = lines.append

    add('"""Replicator script generated by finops-governor (M9 adapter).')
    add("")
    add(f"plan:  {plan.plan_id}")
    add(f"scene: {scene.scene_id} ({scene.variation_count} variations)")
    add("Run inside Isaac Sim (headless):")
    add("  ./python.sh <this file>   # or via isaac-sim.headless with script arg")
    add('"""')
    add("")
    add("import omni.replicator.core as rep")
    add("")
    # Render mode + quality from the plan's render settings
    if rs.renderer is RendererType.PATH_TRACED:
        add(f"rep.settings.set_render_pathtraced(samples_per_pixel={rs.samples_per_pixel})")
    else:
        add("rep.settings.set_render_rtx_realtime()")
    add("")
    add("with rep.new_layer():")
    add(f"    environment = rep.create.from_usd({scene.environment.usd_path!r})")
    for i, asset in enumerate(scene.assets):
        add(f"    asset_{i} = rep.create.from_usd({asset.usd_path!r})  # {asset.asset_id}")
    asset_group = ", ".join(f"asset_{i}" for i in range(len(scene.assets)))
    add(f"    assets = rep.create.group([{asset_group}])")
    add("")
    for i, camera in enumerate(scene.cameras):
        t, r = camera.transform.translation, camera.transform.rotation
        add(
            f"    camera_{i} = rep.create.camera("
            f"position={tuple(t)}, rotation={tuple(r)})  # {camera.camera_id}"
        )
    products = ", ".join(
        f"rep.create.render_product(camera_{i}, ({rs.width}, {rs.height}))"
        for i in range(len(scene.cameras))
    )
    add(f"    render_products = [{products}]")
    add("")
    # Randomization: the declared block through the v1 registry
    randomizer_body = _randomizer_lines(scene)
    add(f"    with rep.trigger.on_frame(num_frames={scene.variation_count}):")
    lines.extend(f"        {line}" if line else "" for line in randomizer_body)
    add("")
    # Writer: modalities -> BasicWriter annotators
    writer_flags, skipped = _writer_flags(plan)
    for modality in skipped:
        add(f"    # WARNING: modality {modality.value} has no BasicWriter annotator; skipped (v1).")
    add('    writer = rep.WriterRegistry.get("BasicWriter")')
    flag_args = ", ".join(f"{flag}=True" for flag in writer_flags)
    add(f"    writer.initialize(output_dir={output_dir!r}, {flag_args})")
    add("    writer.attach(render_products)")
    add("")
    return "\n".join(lines)


# ---------------------------------------------------------------------- #


def _writer_flags(plan: GenerationPlan) -> tuple[list[str], list[OutputModality]]:
    flags: list[str] = []
    skipped: list[OutputModality] = []
    for modality in plan.modalities:
        flag = _WRITER_FLAGS.get(modality)
        if flag is None:
            skipped.append(modality)
        else:
            flags.append(flag)
    return flags, skipped


def _kind_of(param: RandomizationParameter) -> str | None:
    name = param.name.lower()
    for needles, kind in _PARAM_KINDS:
        if any(n in name for n in needles):
            return kind
    return None


def _choices(param: RandomizationParameter, lo: float, hi: float) -> str:
    """`levels` evenly spaced values across [lo, hi] - the declared capacity, honored."""
    lo = param.min_value if param.min_value is not None else lo
    hi = param.max_value if param.max_value is not None else hi
    k = param.levels
    if k == 1:
        values = [lo]
    else:
        step = (hi - lo) / (k - 1)
        values = [round(lo + i * step, 4) for i in range(k)]
    return repr(values)


def _randomizer_lines(scene: Scene) -> list[str]:
    if scene.randomization is None:
        return ["pass  # no randomization declared; frames vary only by sampler noise"]
    out: list[str] = []
    for param in scene.randomization.parameters:
        kind = _kind_of(param)
        if kind == "rotation":
            out.append(
                f"rep.modify.pose(input_prims=assets, rotation=rep.distribution.choice("
                f"[(0, y, 0) for y in {_choices(param, 0.0, 360.0)}]))  # {param.name}"
            )
        elif kind == "position":
            out.append(
                f"rep.modify.pose(input_prims=assets, position=rep.distribution.choice("
                f"[(x, 0, x) for x in {_choices(param, -2.0, 2.0)}]))  # {param.name}"
            )
        elif kind == "light":
            out.append(
                f"rep.create.light(light_type='Sphere', position=(0, 4, 0), "
                f"intensity=rep.distribution.choice({_choices(param, 300.0, 3000.0)}))"
                f"  # {param.name}"
            )
        elif kind == "color":
            out.append(
                f"rep.randomizer.color(assets, colors=rep.distribution.choice("
                f"[(c, c, c) for c in {_choices(param, 0.1, 0.9)}]))  # {param.name}"
            )
        else:
            out.append(
                f"# WARNING: parameter {param.name!r} ({param.levels} levels) has no "
                f"v1 registry mapping; NOT randomized. The gate's coverage judgment "
                f"trusted this declaration."
            )
    return out
